module radiation_portfolio_dashboard
    implicit none

    integer, parameter :: field_len = 256
    integer, parameter :: max_fields = 32
    integer, parameter :: line_len = 2048

contains

    subroutine run_menu()
        character(len=32) :: choice
        logical :: done

        done = .false.
        do while (.not. done)
            call clear_spacing()
            call print_banner()
            write (*, '(a)') 'Choose a section:'
            write (*, '(a)') '  1  Source map and FDS context'
            write (*, '(a)') '  2  Project 1: Singh & Hostikka hydrogen/H2O data'
            write (*, '(a)') '  3  Project 2: Johansson particle correlations'
            write (*, '(a)') '  4  Project 3: DOM on published fields'
            write (*, '(a)') '  5  Project 4: ML surrogate metrics'
            write (*, '(a)') '  6  Full summary'
            write (*, '(a)') '  7  Write HTML dashboard'
            write (*, '(a)') '  q  Quit'
            write (*, '(a)', advance='no') 'Selection: '
            read (*, '(a)') choice

            select case (trim(adjustl(choice)))
            case ('1')
                call clear_spacing()
                call show_sources()
                call pause_for_enter()
            case ('2')
                call clear_spacing()
                call show_project1()
                call pause_for_enter()
            case ('3')
                call clear_spacing()
                call show_project2()
                call pause_for_enter()
            case ('4')
                call clear_spacing()
                call show_project3()
                call pause_for_enter()
            case ('5')
                call clear_spacing()
                call show_project4()
                call pause_for_enter()
            case ('6')
                call clear_spacing()
                call print_full_summary()
                call pause_for_enter()
            case ('7')
                call write_html_dashboard('outputs/fortran_dashboard.html')
                call pause_for_enter()
            case ('q', 'Q')
                done = .true.
            case default
                write (*, '(a)') 'Unknown selection.'
                call pause_for_enter()
            end select
        end do
    end subroutine run_menu

    subroutine print_full_summary()
        call print_banner()
        call show_sources()
        call show_project1()
        call show_project2()
        call show_project3()
        call show_project4()
    end subroutine print_full_summary

    subroutine print_banner()
        call print_rule()
        write (*, '(a)') 'Non-Gray Thermal Radiation Portfolio - Fortran UI'
        write (*, '(a)') 'Reads published-data CSV artifacts generated by scripts/run_all.py'
        call print_rule()
    end subroutine print_banner

    subroutine show_sources()
        call section_title('Source map and FDS context')
        write (*, '(a)') 'Primary research-team sources encoded in this repo:'
        write (*, '(a)') '  - Singh & Hostikka, Applied Thermal Engineering 294 (2026) 130593'
        write (*, '(a)') '  - Rashidzadeh et al., Fire Safety Journal 160 (2026) 104606'
        write (*, '(a)') '  - Hostikka & Rashidzadeh, Fire Safety Journal 161 (2026) 104677'
        write (*, '(a)') 'Supporting particle-property source:'
        write (*, '(a)') '  - Johansson, International Journal of Heat and Mass Transfer 108 (2017) 519-528'
        write (*, '(a)') 'Web context:'
        write (*, '(a)') '  - Aalto THERAD: Mie absorption/scattering and fire radiation sensing context'
        write (*, '(a)') '  - firemodels/fds: FDS implementation target and Fortran-heavy fire-CFD codebase'
        write (*, '(a)') ''
        write (*, '(a)') 'Portfolio boundary: this is a Fortran dashboard/prototype, not an FDS patch.'
        write (*, '(a)') ''
    end subroutine show_sources

    subroutine show_project1()
        call section_title('Project 1: published hydrogen/H2O radiation data')
        write (*, '(a)') 'Encoded Singh & Hostikka Eq. (21):'
        write (*, '(a)') '  kappa_planck = X_H2O * 3.8821e6 * T^-1.9811'
        write (*, '(a)') ''
        call print_csv_table('outputs/project1_real_hydrogen/tables/singh_model_error_summary.csv', 10)
        call print_csv_table('outputs/project1_real_hydrogen/tables/singh_table2_cpu_times.csv', 10)
        call print_csv_table('outputs/project1_real_hydrogen/tables/singh_table3_wall_emission_errors.csv', 10)
    end subroutine show_project1

    subroutine show_project2()
        call section_title('Project 2: Johansson particle correlations')
        write (*, '(a)') 'Published correlation form: 1 / y^z = 1 / y0^z + 1 / y_inf^z'
        write (*, '(a)') 'Tables below encode coal/char and ash gray Q_abs/Q_scat correlations.'
        write (*, '(a)') ''
        call print_csv_table('outputs/project2_real_particles/tables/johansson_correlation_parameters.csv', 12)
        call print_csv_table('outputs/project2_real_particles/tables/johansson_particle_efficiencies.csv', 6)
    end subroutine show_project2

    subroutine show_project3()
        call section_title('Project 3: DOM on published fields')
        write (*, '(a)') 'The DOM profiles use Singh & Hostikka radial/axial thermodynamic fields.'
        write (*, '(a)') 'These are transparent 1-D checks, not a reproduction of their full 2-D LBL/RCFSK solution.'
        write (*, '(a)') ''
        call summarize_dom_profile('outputs/project3_real_dom/tables/radial_midline_dom_profile.csv', &
                                   'radial midline')
        call summarize_dom_profile('outputs/project3_real_dom/tables/axial_centerline_dom_profile.csv', &
                                   'axial centerline')
        call print_csv_table('outputs/project3_real_dom/tables/published_model_error_summary.csv', 10)
    end subroutine show_project3

    subroutine show_project4()
        call section_title('Project 4: ML surrogate on published H2O correlation')
        write (*, '(a)') 'Target: log10 of the Singh & Hostikka H2O Planck-mean absorption correlation.'
        write (*, '(a)') ''
        call print_csv_table('outputs/project4_real_surrogate/tables/surrogate_metrics.csv', 5)
    end subroutine show_project4

    subroutine summarize_dom_profile(path, label)
        character(len=*), intent(in) :: path
        character(len=*), intent(in) :: label
        character(len=line_len) :: line
        character(len=field_len) :: fields(max_fields)
        integer :: unit, ios, nfields, count
        real(8) :: heat_flux, source_term
        real(8) :: flux_min, flux_max, source_min, source_max

        if (.not. file_exists(path)) then
            write (*, '(a)') 'Missing DOM profile: '//trim(path)
            call print_run_hint()
            return
        end if

        open (newunit=unit, file=path, status='old', action='read', iostat=ios)
        if (ios /= 0) then
            write (*, '(a)') 'Could not open '//trim(path)
            return
        end if

        read (unit, '(a)', iostat=ios) line
        count = 0
        flux_min = huge(1.0d0)
        flux_max = -huge(1.0d0)
        source_min = huge(1.0d0)
        source_max = -huge(1.0d0)

        do
            read (unit, '(a)', iostat=ios) line
            if (ios /= 0) exit
            call split_csv(line, fields, nfields)
            if (nfields >= 6) then
                heat_flux = parse_real(fields(5))
                source_term = parse_real(fields(6))
                flux_min = min(flux_min, heat_flux)
                flux_max = max(flux_max, heat_flux)
                source_min = min(source_min, source_term)
                source_max = max(source_max, source_term)
                count = count + 1
            end if
        end do
        close (unit)

        write (*, '(a)') 'DOM summary: '//trim(label)
        write (*, '(a,i0)') '  samples: ', count
        write (*, '(a,es12.4,a,es12.4)') '  heat flux range [W/m2]: ', flux_min, ' to ', flux_max
        write (*, '(a,es12.4,a,es12.4)') '  source term range [W/m3]: ', source_min, ' to ', source_max
        write (*, '(a)') ''
    end subroutine summarize_dom_profile

    subroutine print_csv_table(path, max_rows)
        character(len=*), intent(in) :: path
        integer, intent(in) :: max_rows
        character(len=line_len) :: line
        character(len=field_len) :: fields(max_fields)
        integer :: unit, ios, nfields, row

        if (.not. file_exists(path)) then
            write (*, '(a)') 'Missing table: '//trim(path)
            call print_run_hint()
            write (*, '(a)') ''
            return
        end if

        open (newunit=unit, file=path, status='old', action='read', iostat=ios)
        if (ios /= 0) then
            write (*, '(a)') 'Could not open table: '//trim(path)
            return
        end if

        write (*, '(a)') 'CSV: '//trim(path)
        read (unit, '(a)', iostat=ios) line
        if (ios == 0) then
            call split_csv(line, fields, nfields)
            write (*, '(a)') '  '//trim(join_fields(fields, nfields, ' | '))
            write (*, '(a)') '  '//repeat('-', min(76, len_trim(join_fields(fields, nfields, ' | '))))
        end if

        row = 0
        do while (row < max_rows)
            read (unit, '(a)', iostat=ios) line
            if (ios /= 0) exit
            call split_csv(line, fields, nfields)
            write (*, '(a)') '  '//trim(join_fields(fields, nfields, ' | '))
            row = row + 1
        end do
        close (unit)
        write (*, '(a)') ''
    end subroutine print_csv_table

    subroutine write_html_dashboard(output_path)
        character(len=*), intent(in) :: output_path
        integer :: unit, ios

        open (newunit=unit, file=output_path, status='replace', action='write', iostat=ios)
        if (ios /= 0) then
            write (*, '(a)') 'Could not write HTML file: '//trim(output_path)
            return
        end if

        write (unit, '(a)') '<!doctype html>'
        write (unit, '(a)') '<html lang="en"><head><meta charset="utf-8">'
        write (unit, '(a)') '<meta name="viewport" content="width=device-width, initial-scale=1">'
        write (unit, '(a)') '<title>Thermal Radiation Portfolio Dashboard</title>'
        call write_html_style(unit)
        write (unit, '(a)') '</head><body>'
        write (unit, '(a)') '<main>'
        write (unit, '(a)') '<h1>Non-Gray Thermal Radiation Portfolio</h1>'
        write (unit, '(a)') '<p>Fortran-generated dashboard reading real published-data CSV artifacts.</p>'
        write (unit, '(a)') '<section><h2>Source Basis</h2>'
        write (unit, '(a)') '<ul>'
        write (unit, '(a)') '<li>Singh &amp; Hostikka, Applied Thermal Engineering 294 (2026) 130593.</li>'
        write (unit, '(a)') '<li>Rashidzadeh et al., Fire Safety Journal 160 (2026) 104606.</li>'
        write (unit, '(a)') '<li>Hostikka &amp; Rashidzadeh, Fire Safety Journal 161 (2026) 104677.</li>'
        write (unit, '(a)') '<li>Johansson, International Journal of Heat and Mass Transfer 108 (2017) 519-528.</li>'
        write (unit, '(a)') '</ul></section>'

        call write_html_csv_section(unit, 'Project 1: published model errors', &
                                    'outputs/project1_real_hydrogen/tables/singh_model_error_summary.csv', 20)
        call write_html_csv_section(unit, 'Project 1: CPU timings', &
                                    'outputs/project1_real_hydrogen/tables/singh_table2_cpu_times.csv', 20)
        call write_html_csv_section(unit, 'Project 2: Johansson particle correlations', &
                                    'outputs/project2_real_particles/tables/johansson_correlation_parameters.csv', 20)
        call write_html_csv_section(unit, 'Project 3: published model errors', &
                                    'outputs/project3_real_dom/tables/published_model_error_summary.csv', 20)
        call write_html_csv_section(unit, 'Project 4: surrogate metrics', &
                                    'outputs/project4_real_surrogate/tables/surrogate_metrics.csv', 20)

        write (unit, '(a)') '</main></body></html>'
        close (unit)
        write (*, '(a)') 'Wrote '//trim(output_path)
    end subroutine write_html_dashboard

    subroutine write_html_style(unit)
        integer, intent(in) :: unit
        write (unit, '(a)') '<style>'
        write (unit, '(a)') 'body{font-family:Segoe UI,Arial,sans-serif;margin:0;background:#f6f7f9;color:#20242a;}'
        write (unit, '(a)') 'main{max-width:1120px;margin:0 auto;padding:32px;}'
        write (unit, '(a)') 'section{background:white;border:1px solid #d8dde6;margin:18px 0;padding:18px;border-radius:6px;}'
        write (unit, '(a)') 'h1{margin:0 0 8px;} h2{margin-top:0;font-size:1.1rem;}'
        write (unit, '(a)') 'table{border-collapse:collapse;width:100%;font-size:0.9rem;}'
        write (unit, '(a)') 'th,td{border:1px solid #d8dde6;padding:7px 8px;text-align:left;vertical-align:top;}'
        write (unit, '(a)') 'th{background:#eef2f6;} code{background:#eef2f6;padding:2px 4px;border-radius:4px;}'
        write (unit, '(a)') '</style>'
    end subroutine write_html_style

    subroutine write_html_csv_section(unit, title, path, max_rows)
        integer, intent(in) :: unit
        character(len=*), intent(in) :: title, path
        integer, intent(in) :: max_rows
        character(len=line_len) :: line
        character(len=field_len) :: fields(max_fields)
        integer :: csv_unit, ios, nfields, i, row

        write (unit, '(a)') '<section><h2>'//html_escape(title)//'</h2>'
        write (unit, '(a)') '<p><code>'//html_escape(path)//'</code></p>'

        if (.not. file_exists(path)) then
            write (unit, '(a)') '<p>Missing table. Run <code>python scripts/run_all.py</code>.</p></section>'
            return
        end if

        open (newunit=csv_unit, file=path, status='old', action='read', iostat=ios)
        if (ios /= 0) then
            write (unit, '(a)') '<p>Could not open table.</p></section>'
            return
        end if

        write (unit, '(a)') '<table>'
        read (csv_unit, '(a)', iostat=ios) line
        if (ios == 0) then
            call split_csv(line, fields, nfields)
            write (unit, '(a)', advance='no') '<thead><tr>'
            do i = 1, nfields
                write (unit, '(a)', advance='no') '<th>'//html_escape(trim(fields(i)))//'</th>'
            end do
            write (unit, '(a)') '</tr></thead><tbody>'
        end if

        row = 0
        do while (row < max_rows)
            read (csv_unit, '(a)', iostat=ios) line
            if (ios /= 0) exit
            call split_csv(line, fields, nfields)
            write (unit, '(a)', advance='no') '<tr>'
            do i = 1, nfields
                write (unit, '(a)', advance='no') '<td>'//html_escape(trim(fields(i)))//'</td>'
            end do
            write (unit, '(a)') '</tr>'
            row = row + 1
        end do

        close (csv_unit)
        write (unit, '(a)') '</tbody></table></section>'
    end subroutine write_html_csv_section

    subroutine split_csv(line, fields, nfields)
        character(len=*), intent(in) :: line
        character(len=field_len), intent(out) :: fields(max_fields)
        integer, intent(out) :: nfields
        integer :: start_pos, comma_pos, token_end

        fields = ''
        nfields = 0
        start_pos = 1

        do
            if (nfields >= max_fields) exit
            comma_pos = index(line(start_pos:), ',')
            nfields = nfields + 1
            if (comma_pos == 0) then
                fields(nfields) = adjustl(line(start_pos:))
                exit
            else
                token_end = start_pos + comma_pos - 2
                if (token_end >= start_pos) then
                    fields(nfields) = adjustl(line(start_pos:token_end))
                else
                    fields(nfields) = ''
                end if
                start_pos = start_pos + comma_pos
            end if
            if (start_pos > len_trim(line) + 1) exit
        end do
    end subroutine split_csv

    function join_fields(fields, nfields, separator) result(joined)
        character(len=field_len), intent(in) :: fields(max_fields)
        integer, intent(in) :: nfields
        character(len=*), intent(in) :: separator
        character(len=line_len) :: joined
        integer :: i

        joined = ''
        do i = 1, nfields
            if (i > 1) joined = trim(joined)//separator
            joined = trim(joined)//trim(fields(i))
        end do
    end function join_fields

    function parse_real(text) result(value)
        character(len=*), intent(in) :: text
        real(8) :: value
        integer :: ios

        read (text, *, iostat=ios) value
        if (ios /= 0) value = 0.0d0
    end function parse_real

    function file_exists(path) result(exists)
        character(len=*), intent(in) :: path
        logical :: exists

        inquire (file=path, exist=exists)
    end function file_exists

    function html_escape(text) result(escaped)
        character(len=*), intent(in) :: text
        character(len=line_len) :: escaped
        integer :: i
        character(len=1) :: ch

        escaped = ''
        do i = 1, len_trim(text)
            ch = text(i:i)
            select case (ch)
            case ('&')
                escaped = trim(escaped)//'&amp;'
            case ('<')
                escaped = trim(escaped)//'&lt;'
            case ('>')
                escaped = trim(escaped)//'&gt;'
            case ('"')
                escaped = trim(escaped)//'&quot;'
            case default
                escaped = trim(escaped)//ch
            end select
        end do
    end function html_escape

    subroutine section_title(title)
        character(len=*), intent(in) :: title

        call print_rule()
        write (*, '(a)') trim(title)
        call print_rule()
    end subroutine section_title

    subroutine print_rule()
        write (*, '(a)') repeat('=', 78)
    end subroutine print_rule

    subroutine print_run_hint()
        write (*, '(a)') '  Hint: run python scripts/run_all.py before launching this UI.'
    end subroutine print_run_hint

    subroutine pause_for_enter()
        character(len=8) :: dummy

        write (*, '(a)', advance='no') 'Press Enter to continue...'
        read (*, '(a)') dummy
    end subroutine pause_for_enter

    subroutine clear_spacing()
        write (*, '(a)') ''
        write (*, '(a)') ''
    end subroutine clear_spacing

end module radiation_portfolio_dashboard

program radiation_portfolio_ui
    use radiation_portfolio_dashboard
    implicit none

    character(len=128) :: arg

    if (command_argument_count() == 0) then
        call run_menu()
    else
        call get_command_argument(1, arg)
        select case (trim(adjustl(arg)))
        case ('--summary')
            call print_full_summary()
        case ('--html')
            call write_html_dashboard('outputs/fortran_dashboard.html')
        case ('--help', '-h')
            call print_usage()
        case default
            write (*, '(a)') 'Unknown argument: '//trim(arg)
            call print_usage()
        end select
    end if

contains

    subroutine print_usage()
        write (*, '(a)') 'Usage: radiation_portfolio_ui.exe [--summary|--html|--help]'
        write (*, '(a)') 'No arguments launches the interactive terminal UI.'
    end subroutine print_usage

end program radiation_portfolio_ui
